title: Alex Blog

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

# Site configurations
gems:
- jekyll-paginate

paginate: 30
paginate_path: '/page:num'

tag_page: '/tags'